# Generated by Django 5.2.5 on 2025-10-13 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='emaillog',
            new_name='emails_emai_recipie_1053eb_idx',
            old_name='emails_emaillog_recipient_idx',
        ),
        migrations.RenameIndex(
            model_name='emaillog',
            new_name='emails_emai_status_e97e19_idx',
            old_name='emails_emaillog_status_idx',
        ),
        migrations.RenameIndex(
            model_name='emaillog',
            new_name='emails_emai_created_8a5fea_idx',
            old_name='emails_emaillog_created_at_idx',
        ),
    ]
