# Generated by Django 5.2.5 on 2025-11-30 19:21

import django.db.models.deletion
import required_documents.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('api_key', models.CharField(help_text='Unique key used in API calls', max_length=100, unique=True)),
                ('program_type', models.CharField(choices=[('high-school', 'High School Program'), ('bachelor', "Bachelor's Program"), ('master', "Master's Program"), ('all', 'All Programs')], default='all', max_length=20)),
                ('required', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Document Category',
                'verbose_name_plural': 'Document Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DocumentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_name', models.CharField(max_length=255)),
                ('description', models.TextField(help_text='Describe what document is needed and why')),
                ('deadline', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('submitted', 'Submitted'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_document_requests', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document Request',
                'verbose_name_plural': 'Document Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_type', models.CharField(choices=[('high-school', 'High School Program'), ('bachelor', "Bachelor's Program"), ('master', "Master's Program")], max_length=20)),
                ('category_key', models.CharField(help_text='API key for the document category', max_length=100)),
                ('original_filename', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to=required_documents.models.document_upload_path)),
                ('file_size', models.PositiveIntegerField(default=0, help_text='File size in bytes')),
                ('content_type', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('resubmit', 'Resubmission Required')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal admin notes')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='required_documents.documentcategory')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_documents', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document Submission',
                'verbose_name_plural': 'Document Submissions',
                'ordering': ['-uploaded_at'],
                'unique_together': {('user', 'category_key', 'program_type')},
            },
        ),
        migrations.CreateModel(
            name='DocumentFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_type', models.CharField(choices=[('general', 'General Feedback'), ('improvement', 'Improvement Suggestion'), ('issue', 'Issue Found'), ('approval', 'Approval Note'), ('request', 'Document Request')], default='general', max_length=20)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='given_feedback', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_feedback', to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='required_documents.documentsubmission')),
            ],
            options={
                'verbose_name': 'Document Feedback',
                'verbose_name_plural': 'Document Feedback',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentSubmissionBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_type', models.CharField(choices=[('high-school', 'High School Program'), ('bachelor', "Bachelor's Program"), ('master', "Master's Program")], max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('is_complete', models.BooleanField(default=False, help_text='Whether all required documents are submitted')),
                ('submissions', models.ManyToManyField(related_name='batches', to='required_documents.documentsubmission')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document Submission Batch',
                'verbose_name_plural': 'Document Submission Batches',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='UserDocumentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('study_mode', models.CharField(blank=True, choices=[('full-time', 'Full-time'), ('part-time', 'Part-time'), ('online', 'Online/Distance Learning')], max_length=20)),
                ('field_of_study', models.CharField(blank=True, choices=[('computer-science', 'Computer Science & IT'), ('engineering', 'Engineering'), ('business', 'Business & Management'), ('medicine', 'Medicine & Health Sciences'), ('law', 'Law'), ('arts', 'Arts & Humanities'), ('social-sciences', 'Social Sciences'), ('natural-sciences', 'Natural Sciences'), ('education', 'Education'), ('architecture', 'Architecture & Design'), ('agriculture', 'Agriculture & Environmental'), ('media', 'Media & Communications'), ('hospitality', 'Hospitality & Tourism'), ('other', 'Other')], max_length=50)),
                ('highest_education', models.CharField(blank=True, choices=[('high-school', 'High School / Secondary School'), ('some-college', 'Some College (No Degree)'), ('associate', 'Associate Degree'), ('bachelor', "Bachelor's Degree"), ('master', "Master's Degree"), ('doctorate', 'Doctorate / PhD')], max_length=20)),
                ('applying_to', models.CharField(blank=True, choices=[('high-school', 'High School Program'), ('bachelor', "Bachelor's Degree"), ('master', "Master's Degree")], max_length=20)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='document_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Document Profile',
                'verbose_name_plural': 'User Document Profiles',
            },
        ),
    ]
