# Generated by Django 5.2.5 on 2025-11-30 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('required_documents', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdocumentprofile',
            name='study_mode',
        ),
    ]
