# Generated by Django 5.2.5 on 2025-09-22 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='preferred_intakes',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
