# Generated by Django 5.2.5 on 2025-12-03 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_preferred_intakes'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='referred_by',
            field=models.CharField(blank=True, help_text='Referral code used during registration', max_length=10, null=True),
        ),
    ]
