# Generated by Django 5.2.5 on 2025-12-26 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_agent_cbe_account_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='referred_by',
            field=models.CharField(blank=True, db_index=True, help_text='Referral code used during registration', max_length=10, null=True),
        ),
    ]
