services:
  - type: web
    name: mertservice-api
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn university_api.wsgi:application --bind 0.0.0.0:$PORT --workers 2 --timeout 120"
    envVars:
      - key: DEBUG
        value: "false"
      - key: RENDER
        value: "true"
      - key: SECRET_KEY
        generateValue: true
      - key: USE_LOCAL_DB
        value: "false"
      - key: DATABASE_URL
        value: "postgresql://servicefinder_oexm_user:ZFyo92pkSqbmbC0Abt3MHNTNZfVtEZns@dpg-d6qjfqlm5p6s73e4cb9g-a/servicefinder_oexm"
      - key: ALLOWED_HOSTS
        value: "servicefinder-fvon.onrender.com"
      - key: CSRF_TRUSTED_ORIGINS
        value: "https://servicefinder-fvon.onrender.com"
      - key: EMAIL_HOST_USER
        value: "mertservice@gmail.com"
      - key: EMAIL_HOST_PASSWORD
        sync: false
    disk:
      name: media-storage
      mountPath: /var/data
      sizeGB: 1


