# Generated by Django 5.2.11 on 2026-02-25 18:53

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g., 'Professional Plumbing Services'", max_length=200)),
                ('service_category', models.CharField(help_text="e.g., 'Plumber', 'Electrician', 'Cleaner'", max_length=100)),
                ('description', models.TextField()),
                ('price_type', models.CharField(choices=[('hourly', 'Hourly Rate'), ('fixed', 'Fixed Price')], default='hourly', max_length=20)),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Hourly rate in ETB', max_digits=8, null=True)),
                ('base_price', models.DecimalField(blank=True, decimal_places=2, help_text='Fixed base price in ETB', max_digits=8, null=True)),
                ('latitude', models.DecimalField(decimal_places=6, help_text='Latitude coordinate (e.g., 9.032000)', max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, help_text='Longitude coordinate (e.g., 38.757800)', max_digits=9)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(default='Ethiopia', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Service is active and visible')),
                ('verification_status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('views_count', models.IntegerField(default=0)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Provider Service',
                'verbose_name_plural': 'Provider Services',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('duration', models.IntegerField(blank=True, help_text='Call duration in seconds (future feature)', null=True)),
                ('caller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calls_made', to=settings.AUTH_USER_MODEL)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calls_received', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='providers.providerservice')),
            ],
            options={
                'verbose_name': 'Call Log',
                'verbose_name_plural': 'Call Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ProviderVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verification_type', models.CharField(choices=[('national_id', 'National ID'), ('payment_proof', 'Payment Proof')], max_length=20)),
                ('file', models.FileField(help_text='Upload National ID or Payment Proof screenshot', upload_to='verifications/%Y/%m/')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason for rejection (if applicable)')),
                ('expiry_date', models.DateField(blank=True, help_text='ID expiry date (for National ID only)', null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_providers', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Provider Verification',
                'verbose_name_plural': 'Provider Verifications',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(help_text='Rating from 1 to 5 stars', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_given', to=settings.AUTH_USER_MODEL)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_received', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='providers.providerservice')),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProviderProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_id_verified', models.BooleanField(default=False, help_text='National ID has been verified by admin')),
                ('payment_verified', models.BooleanField(default=False, help_text='Payment proof has been verified by admin')),
                ('is_verified', models.BooleanField(default=False, help_text='Provider is fully verified and visible to clients')),
                ('services_count', models.IntegerField(default=0, help_text='Current number of active services')),
                ('max_services_allowed', models.IntegerField(default=3, help_text='Maximum services allowed (admin can override)')),
                ('phone_number', models.CharField(max_length=20)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, help_text='Latitude coordinate (e.g., 9.032000)', max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, help_text='Longitude coordinate (e.g., 38.757800)', max_digits=9, null=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(default='Ethiopia', max_length=100)),
                ('rating', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
                ('total_reviews', models.IntegerField(default=0)),
                ('subscription_status', models.CharField(choices=[('none', 'None'), ('active', 'Active'), ('expired', 'Expired')], default='none', max_length=10)),
                ('subscription_end_date', models.DateField(blank=True, null=True)),
                ('total_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('months_subscribed', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='provider_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Provider Profile',
                'verbose_name_plural': 'Provider Profiles',
                'indexes': [models.Index(fields=['is_verified'], name='providers_p_is_veri_4fb35c_idx'), models.Index(fields=['city'], name='providers_p_city_8c503d_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='providerservice',
            index=models.Index(fields=['provider', 'is_active'], name='providers_p_provide_ef492f_idx'),
        ),
        migrations.AddIndex(
            model_name='providerservice',
            index=models.Index(fields=['service_category'], name='providers_p_service_32dd67_idx'),
        ),
        migrations.AddIndex(
            model_name='providerservice',
            index=models.Index(fields=['city'], name='providers_p_city_3270c1_idx'),
        ),
        migrations.AddIndex(
            model_name='providerservice',
            index=models.Index(fields=['verification_status'], name='providers_p_verific_13104b_idx'),
        ),
        migrations.AddIndex(
            model_name='calllog',
            index=models.Index(fields=['caller', 'timestamp'], name='providers_c_caller__5067b1_idx'),
        ),
        migrations.AddIndex(
            model_name='calllog',
            index=models.Index(fields=['provider', 'timestamp'], name='providers_c_provide_45209e_idx'),
        ),
        migrations.AddIndex(
            model_name='providerverification',
            index=models.Index(fields=['user', 'verification_type'], name='providers_p_user_id_da966b_idx'),
        ),
        migrations.AddIndex(
            model_name='providerverification',
            index=models.Index(fields=['status'], name='providers_p_status_4792f6_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['provider', 'rating'], name='providers_r_provide_f79a79_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('client', 'provider', 'service')},
        ),
    ]
