# Generated by Django 5.2.11 on 2026-03-03 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0007_add_is_active_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='otpverification',
            new_name='providers_o_phone_n_00cad8_idx',
            old_name='providers_o_phone_n_idx',
        ),
        migrations.RenameIndex(
            model_name='providerprofile',
            new_name='providers_p_subscri_afc61a_idx',
            old_name='providers_p_subscri_idx',
        ),
        migrations.RenameIndex(
            model_name='providerprofile',
            new_name='providers_p_trial_e_ca1a3e_idx',
            old_name='providers_p_trial_e_idx',
        ),
        migrations.AlterField(
            model_name='providerprofile',
            name='payment_verified',
            field=models.BooleanField(default=False, help_text='Payment proof has been verified by admin (optional for trial)'),
        ),
    ]
