# Generated by Django 5.2.11 on 2026-03-14 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0010_add_kyc_images_to_provider_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providerprofile',
            name='id_image',
            field=models.FileField(blank=True, help_text='Government-issued ID photo', null=True, upload_to='kyc/ids/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='providerprofile',
            name='selfie_image',
            field=models.FileField(blank=True, help_text='Real-time selfie taken during onboarding', null=True, upload_to='kyc/selfies/%Y/%m/'),
        ),
    ]
