# Generated by Django 5.2.11 on 2026-03-16 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0012_taxonomy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providerservice',
            name='service_category',
            field=models.CharField(help_text='Legacy text field — use subcategory FK for new services', max_length=100),
        ),
    ]
