# Generated by Django 5.2.11 on 2026-04-10 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0013_alter_providerservice_service_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='providerverification',
            name='verification_type',
            field=models.CharField(choices=[('national_id', 'National ID'), ('payment_proof', 'Payment Proof'), ('selfie', 'Selfie Photo')], max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
