# Generated by Django 5.2.11 on 2026-04-11 16:55

from django.db import migrations, models


def add_fields_safely(apps, schema_editor):
    """
    Add fields safely - checks if they exist first.
    Works on both PostgreSQL and SQLite.
    """
    from django.db import connection
    
    with connection.cursor() as cursor:
        # Add is_email_verified if it doesn't exist
        try:
            cursor.execute("""
                ALTER TABLE providers_userprofile 
                ADD COLUMN is_email_verified BOOLEAN DEFAULT FALSE NOT NULL;
            """)
            print("✅ Added is_email_verified column")
        except Exception as e:
            if 'already exists' in str(e).lower() or 'duplicate column' in str(e).lower():
                print("⏭️ is_email_verified already exists, skipping")
            else:
                print(f"⚠️ Error adding is_email_verified: {e}")


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0013_alter_providerservice_service_category'),
    ]

    operations = [
        # Safely add is_email_verified
        migrations.RunPython(
            add_fields_safely,
            migrations.RunPython.noop
        ),
        # These are safe to run multiple times - they just update definitions
        migrations.AlterField(
            model_name='providerverification',
            name='verification_type',
            field=models.CharField(
                choices=[
                    ('national_id', 'National ID'),
                    ('payment_proof', 'Payment Proof'),
                    ('selfie', 'Selfie Photo')
                ],
                max_length=20
            ),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
