# Generated by Django 5.2.11 on 2026-04-11 16:55

from django.db import migrations


class Migration(migrations.Migration):
    """
    No-op migration. All changes were already applied in 0014_add_selfie_verification_type.
    This migration exists only to maintain migration history consistency.
    """

    dependencies = [
        ('providers', '0014_add_selfie_verification_type'),
    ]

    operations = [
        # No operations needed - 0014 already added:
        # - is_email_verified field to UserProfile
        # - 'selfie' to ProviderVerification.verification_type choices
        # - Made phone_number nullable
    ]
