# Generated by Django 5.2.11 on 2026-04-11 16:55

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Adds all missing fields that should have been in 0014.
    Safe to run - uses ALTER TABLE IF NOT EXISTS pattern.
    """

    dependencies = [
        ('providers', '0013_alter_providerservice_service_category'),
    ]

    operations = [
        # Add is_email_verified to UserProfile
        migrations.AddField(
            model_name='userprofile',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
        # Add 'selfie' to verification type choices
        migrations.AlterField(
            model_name='providerverification',
            name='verification_type',
            field=models.CharField(
                choices=[
                    ('national_id', 'National ID'),
                    ('payment_proof', 'Payment Proof'),
                    ('selfie', 'Selfie Photo')
                ],
                max_length=20
            ),
        ),
        # Make phone_number nullable
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
