"""
Django settings for university_api project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

from datetime import timedelta
import os
from dotenv import load_dotenv
import dj_database_url

load_dotenv()

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'AUTH_HEADER_TYPES': ('Bearer',),
}

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-yt)2uovn6ck=nwxdrvh#^jr7@o1wrsg%&&!cmp(gxn%f==hl+y')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'False').lower() == 'true'

# Use environment variables for allowed hosts
ALLOWED_HOSTS_str = os.environ.get('ALLOWED_HOSTS', 'localhost,127.0.0.1,uni-find-api.onrender.com')
ALLOWED_HOSTS = [host.strip() for host in ALLOWED_HOSTS_str.split(',')]

# Ensure known Render domains are always included
for domain in ['uni-find-api.onrender.com', 'servicefinder-fvon.onrender.com']:
    if domain not in ALLOWED_HOSTS:
        ALLOWED_HOSTS.append(domain)

# Add local network IPs for mobile testing
for ip in ['192.168.1.8', '192.168.8.50']:
    if ip not in ALLOWED_HOSTS:
        ALLOWED_HOSTS.append(ip)

# Allow all local network IPs in development
if DEBUG:
    ALLOWED_HOSTS.append('*')

# CSRF trusted origins
CSRF_TRUSTED_ORIGINS = os.environ.get('CSRF_TRUSTED_ORIGINS', '').split(',') if os.environ.get('CSRF_TRUSTED_ORIGINS') else []
if 'https://servicefinder-fvon.onrender.com' not in CSRF_TRUSTED_ORIGINS:
    CSRF_TRUSTED_ORIGINS.append('https://servicefinder-fvon.onrender.com')

# Trust the 'X-Forwarded-Proto' header from the reverse proxy (like Render)
# This ensures request.build_absolute_uri() generates https:// URLs correctly.
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# allow frontend to access backend
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5174",
    "http://localhost:5173",
    "http://localhost:4173",
    "http://localhost:19006",  # Expo web default port
    "http://localhost:19000",  # Expo Metro bundler
    "http://localhost:8081",   # Expo web dev server
    "http://localhost:8082",
    "https://uni-frontend-lac.vercel.app",
    "https://skyblue-ibis-580217.hostingersite.com",
    "https://addistemari.com",
]
CORS_ALLOW_ALL_ORIGINS = True  # Allow all origins (handles dynamic ports)
CORS_ALLOW_CREDENTIALS = True

# Additional CORS settings for development
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]




# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'rest_framework',
     'universities',

     'corsheaders',
     'django_filters',

     'djoser',
     'rest_framework.authtoken',
     'rest_framework_simplejwt',
     
     'contacts',
     'profiles',
     'notifications',
     'content_creator',
     'payments',
     'gamification',
     'emails',
     'essays',
     'required_documents',
     'recommendations',
     'django_celery_beat',
     'django_celery_results',
     'providers',  # SQLite-safe provider app (no PostGIS)
]

REST_FRAMEWORK = {
    'DEFAULT_FILTER_BACKENDS': ['django_filters.rest_framework.DjangoFilterBackend'],
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
}

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
     'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'university_api.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'university_api.wsgi.application'

# Media files — use Render persistent disk in production, local /media in dev
if os.environ.get('RENDER'):
    MEDIA_ROOT = os.path.join('/var/data', 'media')
else:
    MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Database configuration
# IMPORTANT: Always use SQLite for local development to avoid affecting remote PostgreSQL
# For production deployment: DATABASE_URL is set on Render

# Force SQLite for local development (safer approach)
_use_local_raw = os.environ.get('USE_LOCAL_DB', 'true').strip().lower()
USE_LOCAL_DB = _use_local_raw not in ('false', '0', 'no')

# Also treat presence of RENDER env var as "use remote DB"
IS_RENDER = os.environ.get('RENDER', '').strip().lower() in ('true', '1', 'yes')
if IS_RENDER:
    USE_LOCAL_DB = False

if 'DATABASE_URL' in os.environ and not USE_LOCAL_DB:
    print(f"⚠️  Using remote DATABASE_URL: {os.environ.get('DATABASE_URL', 'Not set')[:50]}...")
    
    # Parse the database URL
    DATABASES = {
        'default': dj_database_url.config(
            default=os.environ.get('DATABASE_URL'),
            conn_max_age=600,
            conn_health_checks=True,
        )
    }
    
    # Configure SSL for Render PostgreSQL
    # Render requires SSL but with 'prefer' mode to handle connection issues
    if DATABASES['default']['ENGINE'] == 'django.db.backends.postgresql':
        if 'OPTIONS' not in DATABASES['default']:
            DATABASES['default']['OPTIONS'] = {}
        
        # Use 'prefer' SSL mode - tries SSL but falls back if needed
        DATABASES['default']['OPTIONS']['sslmode'] = 'prefer'
        
        # Alternatively, disable SSL verification (less secure but works)
        # Uncomment if 'prefer' doesn't work:
        # DATABASES['default']['OPTIONS']['sslmode'] = 'disable'
else:
    # Local development with SQLite (DEFAULT and RECOMMENDED)
    print("📦 Using local SQLite database for development (safe mode)")
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Deployment on Render

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# WhiteNoise configuration
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'


# media definition

# ... at the end of settings.py

# (MEDIA_ROOT and MEDIA_URL defined above near WSGI_APPLICATION)

#NOTIFICATION AND ASYNC TASKS SETTINGS

# Email Configuration — credentials from environment variables
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_USE_SSL = False
EMAIL_TIMEOUT = 10  # short timeout prevents gunicorn worker kills
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.environ.get('EMAIL_HOST_USER', 'noreply@mertservice.com')

# Use real SMTP only when credentials are set; fall back to console logging
if EMAIL_HOST_USER and EMAIL_HOST_PASSWORD:
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
else:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'


# Celery Configuration
CELERY_BROKER_URL = os.environ.get("CELERY_BROKER_URL", "redis://localhost:6379/0")
CELERY_RESULT_BACKEND = os.environ.get("CELERY_RESULT_BACKEND", "redis://localhost:6379/0")
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'UTC'

# Celery Beat (for scheduled tasks)
CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'
CELERY_BEAT_SCHEDULE = {
    'check-subscription-expiry-every-day': {
        'task': 'profiles.tasks.check_subscription_expirations',
        'schedule': 86400.0,  # Run once every 24 hours (in seconds)
    },
}

# ScholarshipOwl API Configuration
SCHOLARSHIPOWL_API_KEY = os.environ.get('SCHOLARSHIPOWL_API_KEY')
