# Generated by Django 5.2.5 on 2025-09-29 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_creator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationsettings',
            name='creators_needed',
            field=models.PositiveIntegerField(default=5, help_text='Number of creators needed'),
        ),
    ]
