# Generated by Django 5.2.5 on 2025-09-29 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_creator', '0002_applicationsettings_creators_needed'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunitypost',
            name='has_premium_section',
            field=models.BooleanField(default=False, help_text='Has premium content section'),
        ),
        migrations.AddField(
            model_name='opportunitypost',
            name='premium_content',
            field=models.TextField(blank=True, help_text='Premium content only visible to subscribers'),
        ),
        migrations.AlterField(
            model_name='opportunitypost',
            name='content',
            field=models.TextField(help_text='Public content visible to all users'),
        ),
        migrations.AlterField(
            model_name='opportunitypost',
            name='opportunity_link',
            field=models.URLField(blank=True, help_text='Premium link to opportunity'),
        ),
    ]
