# Generated by Django 5.2.5 on 2025-09-29 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_creator', '0003_opportunitypost_has_premium_section_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunitypost',
            name='is_draft',
            field=models.BooleanField(default=False, help_text='Save as draft (not published)'),
        ),
    ]
