# Generated by Django 5.2.5 on 2025-09-29 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_creator', '0004_opportunitypost_is_draft'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationsettings',
            name='is_open',
            field=models.BooleanField(default=False, help_text='Allow new creator applications - only open when spots are available'),
        ),
    ]
