# Generated by Django 5.2.5 on 2025-09-29 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_creator', '0005_alter_applicationsettings_is_open'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationsettings',
            name='show_creator_tab',
            field=models.BooleanField(default=False, help_text='Show creator application tab to users'),
        ),
    ]
