# Generated by Django 5.2.5 on 2025-09-29 08:39

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreatorApplicationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applications_open', models.BooleanField(default=False)),
                ('application_deadline', models.DateTimeField(blank=True, null=True)),
                ('max_applications', models.IntegerField(default=100)),
                ('current_applications', models.IntegerField(default=0)),
                ('requirements', models.TextField(default='', help_text='Requirements for becoming a creator')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Creator Application Settings',
                'verbose_name_plural': 'Creator Application Settings',
            },
        ),
        migrations.CreateModel(
            name='CreatorApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivation', models.TextField(help_text='Why do you want to become a creator?')),
                ('expertise_areas', models.JSONField(default=list, help_text='Areas of expertise')),
                ('experience', models.TextField(help_text='Relevant experience')),
                ('sample_content', models.TextField(help_text='Sample content or portfolio')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True, help_text='Admin review notes')),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='creator_application', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-applied_at'],
            },
        ),
        migrations.CreateModel(
            name='CreatorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('expertise_areas', models.JSONField(default=list, help_text="Areas of expertise like 'scholarships', 'visa', 'applications'")),
                ('total_earnings', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('active_subscribers', models.IntegerField(default=0)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_approved_creator', models.BooleanField(default=False, help_text='Approved to create content')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='creator_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content_type', models.CharField(choices=[('scholarship', 'Scholarship'), ('internship', 'Internship'), ('job', 'Job Opportunity'), ('exchange', 'Exchange Program'), ('tutorial', 'Tutorial/Guide'), ('result', 'Success Story/Result'), ('insight', 'Country/University Insight'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField(help_text='Public preview description', max_length=1000)),
                ('content', models.TextField(help_text='Full content visible to premium users')),
                ('opportunity_links', models.JSONField(default=list, help_text='Hidden links for premium users')),
                ('tags', models.JSONField(default=list, help_text='Tags for categorization')),
                ('country', models.CharField(blank=True, max_length=100)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Review'), ('published', 'Published'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('views_count', models.IntegerField(default=0)),
                ('subscribers_gained', models.IntegerField(default=0, help_text='Subscriptions attributed to this post')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CreatorEarning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('total_subscribers', models.IntegerField(default=0)),
                ('gross_revenue', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('creator_share', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('is_paid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earnings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-month'],
                'unique_together': {('creator', 'month')},
            },
        ),
        migrations.CreateModel(
            name='OpportunityView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='opportunities.opportunity')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('opportunity', 'user', 'ip_address')},
            },
        ),
        migrations.CreateModel(
            name='SubscriptionAttribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_start', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('monthly_share_percentage', models.DecimalField(decimal_places=2, default=Decimal('35.00'), max_digits=5)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributed_subscriptions', to=settings.AUTH_USER_MODEL)),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_attributions', to='opportunities.opportunity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_attributions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'creator')},
            },
        ),
    ]
