# Generated by Django 5.2.5 on 2025-09-19 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0007_userdashboard_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdashboard',
            name='phone_number',
        ),
    ]
