# Generated by Django 5.2.5 on 2025-09-22 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0008_remove_userdashboard_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='degree_level',
            field=models.CharField(blank=True, help_text='e.g., Bachelor, Master, PhD', max_length=100),
        ),
        migrations.AddField(
            model_name='university',
            name='intake_months',
            field=models.CharField(blank=True, help_text='Comma-separated intake months, e.g., January,September', max_length=255),
        ),
    ]
