# Generated by Django 5.2.5 on 2025-09-23 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0009_university_degree_level_university_intake_months'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='university',
            name='deadline_grad',
        ),
        migrations.RemoveField(
            model_name='university',
            name='deadline_undergrad',
        ),
        migrations.RemoveField(
            model_name='university',
            name='intake_months',
        ),
        migrations.AddField(
            model_name='university',
            name='intakes',
            field=models.JSONField(blank=True, default=list, help_text='List of intake periods and their deadlines.'),
        ),
    ]