# Generated by Django 5.2.5 on 2025-09-24 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0010_remove_university_deadline_grad_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniversityJSONImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json_data', models.TextField(help_text='Paste a single JSON object or a list of JSON objects here.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'University JSON Import',
                'verbose_name_plural': 'University JSON Imports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='university',
            name='degree_level',
        ),
    ]
