# Generated by Django 5.2.5 on 2025-09-28 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0012_enhanced_scraper_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='university',
            name='tuition_fee_domestic',
        ),
    ]
