# Generated by Django 5.2.5 on 2025-09-29 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0013_remove_university_tuition_fee_domestic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='university',
            options={},
        ),
        migrations.RemoveField(
            model_name='university',
            name='deposit_amount',
        ),
        migrations.RemoveField(
            model_name='university',
            name='deposit_deadlines',
        ),
        migrations.RemoveField(
            model_name='university',
            name='housing_info',
        ),
        migrations.RemoveField(
            model_name='university',
            name='tuition_fee_international',
        ),
        migrations.RemoveField(
            model_name='university',
            name='visa_requirements',
        ),
        migrations.AlterField(
            model_name='university',
            name='intakes',
            field=models.JSONField(blank=True, default=list, help_text='List of intake periods and their deadlines.'),
        ),
    ]
