# Generated by Django 5.2.5 on 2025-10-02 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0014_alter_university_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdashboard',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userdashboard',
            name='months_subscribed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userdashboard',
            name='total_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
