# Generated by Django 5.2.5 on 2025-10-03 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0015_userdashboard_is_verified_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScholarshipResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(blank=True, max_length=100)),
                ('scholarships_data', models.JSONField(default=list)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('total_count', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Scholarship Result',
                'verbose_name_plural': 'Scholarship Results',
                'ordering': ['-fetched_at'],
            },
        ),
    ]
