# Generated by Django 5.2.7 on 2025-10-13 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0016_scholarshipresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='image_url',
            field=models.URLField(blank=True, help_text='Optional URL to university image', null=True),
        ),
    ]

