# Generated by Django 5.2.5 on 2025-10-13 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0017_university_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='university',
            name='image_url',
        ),
    ]
