# Generated by Django 5.2.5 on 2025-09-27 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='notificationread',
            new_name='notificatio_user_id_c9016a_idx',
            old_name='notifications_user_idx',
        ),
        migrations.RenameIndex(
            model_name='notificationread',
            new_name='notificatio_notific_3daaa3_idx',
            old_name='notifications_notification_idx',
        ),
    ]
