# Generated by Django 5.2.11 on 2026-03-03 13:46

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0001_initial'),
        ('universities', '0018_remove_university_image_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='recommendeduniversity',
            name='unique_user_university_recommendation',
        ),
        migrations.AlterUniqueTogether(
            name='recommendeduniversity',
            unique_together={('user', 'university')},
        ),
    ]
