# Generated by Django 5.2.5 on 2025-11-22 10:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Essay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, help_text='Short description or preview', max_length=1000)),
                ('content', models.JSONField(default=dict, help_text='Rich text content from TipTap editor')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='essays', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Essay',
                'verbose_name_plural': 'Essays',
                'ordering': ['-created_at'],
            },
        ),
    ]
