# Generated by Django 5.2.5 on 2025-11-22 13:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essays', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='essay',
            name='is_template',
            field=models.BooleanField(default=True, help_text='Whether this is a shared template'),
        ),
        migrations.AlterField(
            model_name='essay',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Original creator (optional for templates)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='essays', to=settings.AUTH_USER_MODEL),
        ),
    ]
